//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsultorio_Dental.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int CitaID { get; set; }
        public int PacienteID { get; set; }
        public int DentistaID { get; set; }
        public int MotivoID { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public int Duracion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual Dentista Dentista { get; set; }
        public virtual Motivo Motivo { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
