//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsultorio_Dental.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConsultorioDentalDBEntities : DbContext
    {
        public ConsultorioDentalDBEntities()
            : base("name=ConsultorioDentalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cita> Citas { get; set; }
        public virtual DbSet<Dentista> Dentistas { get; set; }
        public virtual DbSet<Motivo> Motivos { get; set; }
        public virtual DbSet<Paciente> Pacientes { get; set; }
    }
}
